# Generated by Django 5.0.1 on 2024-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_user_facebook_user_insta_user_linkedin_user_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
