# Generated by Django 5.0.1 on 2024-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='githubname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
