# Generated by Django 5.0.1 on 2024-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_user_githubname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='degreeInfo',
            new_name='degree2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='degreeInfo2',
            new_name='degreeDesc',
        ),
        migrations.AddField(
            model_name='user',
            name='degreeDesc2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
